## Setup — Import libraries and load dataset

In [1]:
import pandas as pd
print(pd.__version__)

3.0.3

In [2]:
df = pd.read_csv("data/matches_1930_2022.csv")
df.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

## Exploration — Dataset overview

In [3]:
df.columns.tolist()

['home_team',
 'away_team',
 'home_score',
 'home_xg',
 'home_penalty',
 'away_score',
 'away_xg',
 'away_penalty',
 'home_manager',
 'home_captain',
 'away_manager',
 'away_captain',
 'Attendance',
 'Venue',
 'Officials',
 'Round',
 'Date',
 'Score',
 'Referee',
 'Notes',
 'Host',
 'Year',
 'home_goal',
 'away_goal',
 'home_goal_long',
 'away_goal_long',
 'home_own_goal',
 'away_own_goal',
 'home_penalty_goal',
 'away_penalty_goal',
 'home_penalty_miss_long',
 'away_penalty_miss_long',
 'home_penalty_shootout_goal_long',
 'away_penalty_shootout_goal_long',
 'home_penalty_shootout_miss_long',
 'away_penalty_shootout_miss_long',
 'home_red_card',
 'away_red_card',
 'home_yellow_red_card',
 'away_yellow_red_card',
 'home_yellow_card_long',
 'away_yellow_card_long',
 'home_substitute_in_long',
 'away_substitute_in_long']

In [4]:
df.shape

(964, 44)

In [5]:
df.isnull().sum()

home_team                            0
away_team                            0
home_score                           0
home_xg                            836
home_penalty                       929
away_score                           0
away_xg                            836
away_penalty                       929
home_manager                         0
home_captain                       320
away_manager                         0
away_captain                       320
Attendance                           0
Venue                                0
Officials                          255
Round                                0
Date                                 0
Score                                0
Referee                            255
Notes                              891
Host                                 0
Year                                 0
home_goal                          246
away_goal                          393
home_goal_long                     246
away_goal_long                     393
home_own_goal                      925
away_own_goal                      947
home_penalty_goal                  848
away_penalty_goal                  880
home_penalty_miss_long             958
away_penalty_miss_long             955
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
home_red_card                      913
away_red_card                      910
home_yellow_red_card               941
away_yellow_red_card               933
home_yellow_card_long              343
away_yellow_card_long              337
home_substitute_in_long            224
away_substitute_in_long            217
dtype: int64

In [6]:
pd.set_option('display.max_rows', 100)
df.head(20)

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...
5,England,France,1,2.4,NaN,2,0.9,NaN,Gareth Southgate,Harry Kane,...,NaN,NaN,NaN,NaN,NaN,NaN,['90&rsquor;|1:2|Harry Maguire'],"['43&rsquor;|0:1|Antoine Griezmann', '47&rsquo...",['79&rsquor;|1:2|Raheem Sterling|for Bukayo Sa...,['79&rsquor;|1:2|Kingsley Coman|for Ousmane De...
6,Croatia,Brazil,1,0.6,4.0,1,2.5,2.0,Zlatko Dalić,Luka Modrić,...,NaN,"['2|1:0|Rodrygo', '8|4:2|Marquinhos']",NaN,NaN,NaN,NaN,"['31&rsquor;|0:0|Marcelo Brozović', '117&rsquo...","['25&rsquor;|0:0|Danilo', '68&rsquor;|0:0|Case...",['72&rsquor;|0:0|Nikola Vlašić|for Mario Pašal...,"['56&rsquor;|0:0|Antony|for Raphinha', '64&rsq..."
7,Netherlands,Argentina,2,0.6,3.0,2,1.9,4.0,Louis van Gaal,Virgil van Dijk,...,"['1|0:0|Virgil van Dijk', '3|0:1|Steven Berghu...",['8|2:3|Enzo Fernández'],NaN,NaN,Denzel Dumfries · 120+3,NaN,"['43&rsquor;|0:1|Jurriën Timber', '45+2&rsquor...","['31&rsquor;|0:0|Walter Samuel', '43&rsquor;|0...",['46&rsquor;|0:1|Steven Berghuis|for Steven Be...,['66&rsquor;|0:1|Leandro Paredes|for Rodrigo D...
8,Morocco,Spain,0,0.7,3.0,0,1.0,0.0,Hoalid Regragui,Romain Saïss,...,['5|2:0|Badr Banoun'],"['2|1:0|Pablo Sarabia', '4|2:0|Carlos Soler', ...",NaN,NaN,NaN,NaN,['90&rsquor;|0:0|Romain Saïss'],['77&rsquor;|0:0|Aymeric Laporte'],['66&rsquor;|0:0|Abdessamad Ezzalzouli|for Sof...,['63&rsquor;|0:0|Álvaro Morata|for Marco Asens...
9,Portugal,Switzerland,6,2.3,NaN,1,1.2,NaN,Fernando Santos,Pepe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['43&rsquor;|2:0|Fabian Schär', '59&rsquor;|4:...",['73&rsquor;|5:1|Cristiano Ronaldo|for Gonçalo...,['46&rsquor;|2:0|Eray Cömert|for Fabian Schär'...
10,Japan,Croatia,1,1.2,1.0,1,1.4,3.0,Hajime Moriyasu,Maya Yoshida,...,"['1|0:0|Takumi Minamino', '3|0:1|Kaoru Mitoma'...",['6|1:2|Marko Livaja'],NaN,NaN,NaN,NaN,NaN,"['90&rsquor;|1:1|Mateo Kovačić', '116&rsquor;|...",['64&rsquor;|1:1|Takuma Asano|for Daizen Maeda...,['62&rsquor;|1:1|Ante Budimir|for Bruno Petkov...
11,Brazil,Korea Republic,4,3.6,NaN,1,0.5,NaN,Tite,Thiago Silva,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['44&rsquor;|4:0|Jung Woo-young'],"['63&rsquor;|4:0|Dani Alves|for Éder Militão',...","['46&rsquor;|4:0|Hong Chul|for Kim Jin-su', '4..."
12,France,Poland,3,1.4,NaN,1,1.7,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,['32&rsquor;|0:0|Aurélien Tchouaméni'],"['47&rsquor;|1:0|Bartosz Bereszyński', '88&rsq...",['66&rsquor;|1:0|Youssouf Fofana|for Aurélien ...,['64&rsquor;|1:0|Arkadiusz Milik|for Sebastian...
13,England,Senegal,3,1.0,NaN,0,0.8,NaN,Gareth Southgate,Harry Kane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['76&rsquor;|3:0|Kalidou Koulibaly'],['65&rsquor;|3:0|Jack Grealish|for Phil Foden'...,['46&rsquor;|2:0|Pape Matar Sarr|for Krépin Di...
14,Netherlands,United States,3,1.7,NaN,1,1.5,NaN,Louis van Gaal,Virgil van Dijk,...,NaN,NaN,NaN,NaN,NaN,NaN,"['60&rsquor;|2:0|Teun Koopmeiners', '87&rsquor...",NaN,['46&rsquor;|2:0|Teun Koopmeiners|for Davy Kla...,['46&rsquor;|2:0|Gio Reyna|for Jesús Ferreira'...
15,Argentina,Australia,2,1.6,NaN,1,0.6,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['15&rsquor;|0:0|Jackson Irvine', '38&rsquor;|...",['50&rsquor;|1:0|Lisandro Martínez|for Papu Gó...,['58&rsquor;|2:0|Craig Goodwin|for Riley McGre...
16,Korea Republic,Portugal,2,1.7,NaN,1,1.3,NaN,Sérgio Costa,Son Heung-min,...,NaN,NaN,NaN,NaN,NaN,NaN,"['36&rsquor;|1:1|Lee Kangin', '90+2&rsquor;|2:...",NaN,['66&rsquor;|1:1|Hwang Hee-chan|for Lee Jae-su...,['65&rsquor;|1:1|João Palhinha|for Matheus Nun...
17,Ghana,Uruguay,0,1.6,NaN,2,1.8,NaN,Otto Addo,André Ayew,...,NaN,NaN,NaN,NaN,NaN,NaN,"['86&rsquor;|0:2|Kamaldeen Sulemana', '90+9&rs...","['19&rsquor;|0:0|Darwin Núñez', '60&rsquor;|0:...",['46&rsquor;|0:2|Kamaldeen Sulemana|for Jordan...,['34&rsquor;|0:2|Matías Vecino|for Rodrigo Ben...
18,Cameroon,Brazil,1,0.5,NaN,0,2.5,NaN,Rigobert Song,Vincent Aboubakar,...,NaN,NaN,NaN,NaN,Vincent Aboubakar · 90+3,NaN,"['6&rsquor;|0:0|Nouhou Tolo', '28&rsquor;|0:0|...","['7&rsquor;|0:0|Éder Militão', '85&rsquor;|0:0...",['64&rsquor;|0:0|Karl Toko Ekambi|for Bryan Mb...,"['55&rsquor;|0:0|Everton Ribeiro|for Rodrygo',..."
19,Serbia,Switzerland,2,1.3,NaN,3,2.7,NaN,Dragan Stojković,Dušan Tadić,...,NaN,NaN,NaN,NaN,NaN,NaN,"['47&rsquor;|2:2|Sergej Milinković-Savić', '56...","['15&rsquor;|0:0|Silvan Widmer', '34&rsquor;|1...",['55&rsquor;|2:3|Nemanja Gudelj|for Miloš Velj...,['68&rsquor;|2:3|Edimilson Fernandes|for Djibr...

## Q1 — Which team won the most matches?

In [7]:
home_wins = df[df["home_score"] > df["away_score"]]["home_team"]

away_wins = df[df["away_score"] > df["home_score"]]["away_team"]

wins = pd.concat([home_wins,away_wins]).value_counts()
print(wins)

Brazil                    76
Argentina                 47
Italy                     45
France                    39
Germany                   37
England                   32
Spain                     31
West Germany              31
Netherlands               30
Uruguay                   25
Belgium                   21
Sweden                    19
Portugal                  17
Poland                    17
Mexico                    17
Soviet Union              15
Hungary                   15
Switzerland               14
Yugoslavia                14
Croatia                   13
Austria                   12
Chile                     11
Czechoslovakia            11
Colombia                   9
United States              9
Denmark                    9
Romania                    8
Korea Republic             7
Japan                      7
Paraguay                   7
Nigeria                    6
Costa Rica                 6
Morocco                    5
Cameroon                   5
Ghana                      5
Ecuador                    5
Türkiye                    5
Peru                       5
Senegal                    5
Australia                  4
Saudi Arabia               4
Russia                     4
Scotland                   4
Tunisia                    3
Côte d'Ivoire              3
Bulgaria                   3
Northern Ireland           3
Algeria                    3
IR Iran                    3
Greece                     2
Ukraine                    2
South Africa               2
FR Yugoslavia              2
Norway                     2
Germany DR                 2
Serbia                     2
Republic of Ireland        2
Bosnia and Herzegovina     1
Slovakia                   1
Korea DPR                  1
Wales                      1
Cuba                       1
Slovenia                   1
Czech Republic             1
Jamaica                    1
Name: count, dtype: int64

## Q2 — Which World Cup had the most goals?

In [8]:
df["total_goals"] = df["home_score"] + df["away_score"]

most_goals_worlcup = df.groupby("Year")["total_goals"].sum()

most_goals_worlcup = most_goals_worlcup.sort_values(ascending=False).head(10)
print(most_goals_worlcup)

Year
2022    172
1998    171
2014    171
2018    169
2002    161
2006    147
1982    146
2010    145
1994    141
1954    140
Name: total_goals, dtype: int64

## Q3 — Biggest victory margin

In [9]:
df["goal_difference"] = (df["home_score"] - df["away_score"]).abs()

max_goal_difference = df.loc[df["goal_difference"].idxmax()]
print(max_goal_difference)

home_team                                                                    Hungary
away_team                                                                El Salvador
home_score                                                                        10
home_xg                                                                          NaN
home_penalty                                                                     NaN
away_score                                                                         1
away_xg                                                                          NaN
away_penalty                                                                     NaN
home_manager                                                          Kalman Meszoly
home_captain                                                           Tibor Nyilasi
away_manager                                                      Mauricio Rodriguez
away_captain                                                          Norberto Huezo
Attendance                                                                     23000
Venue                                                           Nuevo Estadio, Elche
Officials                          Ebrahim Al Doy (Referee) · Charles Corver (AR1...
Round                                                              First group stage
Date                                                                      1982-06-15
Score                                                                          10–1
Referee                                                               Ebrahim Al Doy
Notes                                                                            NaN
Host                                                                           Spain
Year                                                                            1982
home_goal                          Tibor Nyilasi · 4|Gábor Pölöskei · 11|László F...
away_goal                                                   Luis Ramírez Zapata · 64
home_goal_long                     ['4&rsquor;|1:0|Tibor Nyilasi', '11&rsquor;|2:...
away_goal_long                                ['64&rsquor;|5:1|Luis Ramírez Zapata']
home_own_goal                                                                    NaN
away_own_goal                                                                    NaN
home_penalty_goal                                                                NaN
away_penalty_goal                                                                NaN
home_penalty_miss_long                                                           NaN
away_penalty_miss_long                                                           NaN
home_penalty_shootout_goal_long                                                  NaN
away_penalty_shootout_goal_long                                                  NaN
home_penalty_shootout_miss_long                                                  NaN
away_penalty_shootout_miss_long                                                  NaN
home_red_card                                                                    NaN
away_red_card                                                                    NaN
home_yellow_red_card                                                             NaN
away_yellow_red_card                                                             NaN
home_yellow_card_long              ['1&rsquor;|0:0|Tibor Nyilasi', '32&rsquor;|3:...
away_yellow_card_long                                                            NaN
home_substitute_in_long            ['56&rsquor;|5:0|László Kiss|for András Törőcs...
away_substitute_in_long            ['26&rsquor;|3:0|Luis Ramírez Zapata|for José ...
total_goals                                                                       11
goal_difference                                                                    9
Name: 651, dtype: object

In [10]:
df[["home_red_card", "home_yellow_red_card"]].dtypes

home_red_card           str
home_yellow_red_card    str
dtype: object

In [11]:
df["home_red_card"].dropna().unique()

<StringArray>
[                   'Paulo Bento · 90+11',
                   'Wayne Hennessey · 86',
                     'Carlos Sánchez · 3',
                  'Antonio Valencia · 50',
                 'Claudio Marchisio · 59',
                        'Ante Rebić · 89',
                         'Alex Song · 40',
                    'Maxi Pereira · 90+4',
                    'Luis Suárez · 120+1',
                    'Yoann Gourcuff · 25',
                   'Nicolás Lodeiro · 81',
                      'Wayne Rooney · 62',
                   'Marco Materazzi · 50',
                    'Tomáš Ujfaluši · 65',
                  'Daniele De Rossi · 28',
                    'Rafael Márquez · 88',
                        'João Pinto · 27',
                        'Nastja Čeh · 81',
                     'Thierry Henry · 25',
                    'Boris Živković · 59',
                     'Laurent Blanc · 76',
                   'Christian Wörns · 40',
                      'Craig Burley · 53',
                     'Gert Verheyen · 54',
                      'Alfred Phiri · 68',
                   'Zinédine Zidane · 71',
                        'Ha Seok-ju · 30',
                  'Patrick Kluivert · 82',
                       'Jonas Thern · 63',
                   'Leonardo Araújo · 43',
                 'Gianluca Pagliuca · 21',
                       'Ion Vlădoiu · 73',
                'Miguel Ángel Nadal · 25',
                'Refik Šabanadžović · 31',
                     'Ricardo Gomes · 85',
                       'Rudi Völler · 22',
                     'Yoon Deok-yeo · 70',
                      'Peter Artner · 33',
                      'Eric Wynalda · 52',
                   'Thomas Berthold · 65',
                     'Frank Arnesen · 88',
                       'Ray Wilkins · 42',
                    'Diego Maradona · 85',
                       'Mal Donaghy · 62',
                 'Gilberto Yearwood · 89',
                      'Ray Richards · 83',
            'Julio Montero Castillo · 69',
                         'Garrincha · 83',
                   'Vladica Popović · 71',
                     'József Bozsik · 71',
 'Zezé Procópio · 14|Arthur Machado · 89']
Length: 51, dtype: str

## Q4 — Which team received the most red cards?

# Note: counts matches with at least one red card, not total red cards

In [12]:
home_reds = df[df["home_red_card"] != 0][["home_team", "home_red_card"]].rename(columns={"home_team": "team"})
away_reds = df[df["away_red_card"] != 0][["away_team", "away_red_card"]].rename(columns={"away_team": "team"})

red_cards = pd.concat([home_reds, away_reds])
red_cards["team"].value_counts

most_red_cards = red_cards["team"].value_counts()
most_red_cards.head(10)

team
Brazil          114
Argentina        88
Italy            83
England          74
France           73
Spain            67
Mexico           60
Uruguay          59
Germany          56
West Germany     56
Name: count, dtype: int64

## Q5 — How many matches ended 0–0?

In [13]:
df[df["total_goals"] == 0].shape[0]

78

## Q6 — Which World Cup had the highest attendance?

In [14]:
most_attendance_worlcup = df.groupby("Year")["Attendance"].sum()

most_attendance_worlcup = most_attendance_worlcup.sort_values(ascending=False).head(5)
print(most_attendance_worlcup)

Year
1994    3587538
2014    3429873
2022    3404252
2006    3352605
2010    3178856
Name: Attendance, dtype: int64

## Q7 — Which team lost the most matches?

In [15]:
home_losses = df[df["home_score"] < df["away_score"]]["home_team"]

away_losses = df[df["away_score"] < df["home_score"]]["away_team"]

losses = pd.concat([home_losses, away_losses]).value_counts()
print(losses)

Mexico                    28
Argentina                 24
Korea Republic            21
Uruguay                   21
England                   20
Belgium                   20
France                    20
United States             20
Sweden                    19
Brazil                    19
Switzerland               19
Spain                     19
Italy                     17
Poland                    15
Chile                     15
Bulgaria                  15
Hungary                   14
Czechoslovakia            14
Saudi Arabia              13
Cameroon                  13
Austria                   13
Japan                     12
Germany                   12
Australia                 12
Nigeria                   12
Portugal                  12
Scotland                  12
Yugoslavia                12
IR Iran                   11
Morocco                   11
Netherlands               11
West Germany              11
Costa Rica                10
Tunisia                   10
Colombia                  10
Peru                      10
Paraguay                  10
Soviet Union              10
Croatia                    9
Denmark                    8
Romania                    8
Ghana                      7
Algeria                    7
Serbia                     6
Canada                     6
Ecuador                    6
Honduras                   6
Greece                     6
Russia                     6
El Salvador                6
Egypt                      5
Korea DPR                  5
Bolivia                    5
Northern Ireland           5
Côte d'Ivoire              5
Senegal                    4
Slovenia                   4
Türkiye                    4
Wales                      3
Qatar                      3
Panama                     3
South Africa               3
Togo                       3
Serbia and Montenegro      3
China PR                   3
United Arab Emirates       3
Iraq                       3
Zaire                      3
Haiti                      3
Norway                     3
Republic of Ireland        3
New Zealand                3
Iceland                    2
Slovakia                   2
Czech Republic             2
Jamaica                    2
Germany DR                 2
Bosnia and Herzegovina     2
Ukraine                    2
Trinidad and Tobago        2
Kuwait                     2
Angola                     1
FR Yugoslavia              1
Israel                     1
Cuba                       1
Dutch East Indies          1
Name: count, dtype: int64

In [16]:
df["Round"].unique()

<StringArray>
[               'Final',    'Third-place match',          'Semi-finals',
       'Quarter-finals',          'Round of 16',          'Group stage',
   'Second group stage',    'First group stage',         'Second round',
          'First round', 'Group stage play-off',          'Final stage']
Length: 12, dtype: str

In [17]:
knockout = df[~df["Round"].isin(['Group stage', 'First group stage', 'Second group stage', 'First round', 'Second round', 'Group stage play-off'])]
knockout.shape[0]

252

## Q8 — What percentage of knockout matches were decided by penalties?

In [18]:
shootouts = knockout["home_penalty_shootout_goal_long"].notna().sum()
total_knockout = knockout.shape[0]
percentage = (shootouts / total_knockout) * 100

print(f"Partidos con tanda: {shootouts}")
print(f"Total eliminatorias: {total_knockout}")
print(f"Porcentaje: {percentage:.1f}%")

Partidos con tanda: 34
Total eliminatorias: 252
Porcentaje: 13.5%

## Q9 — Correlation between yellow cards and goals

In [19]:
df["home_yellows"] = df["home_yellow_card_long"].str.count("&rsquor;").fillna(0)
df["away_yellows"] = df["away_yellow_card_long"].str.count("&rsquor;").fillna(0)
df["total_yellows"] = df["home_yellows"] + df["away_yellows"]

df[["total_yellows", "total_goals"]].corr()

               total_yellows  total_goals
total_yellows        1.00000     -0.17304
total_goals         -0.17304      1.00000

## Final Report — Export to CSVDijiste: clauede, esto si esta bein no son datos muy alejados?

In [20]:
summary = pd.DataFrame({
    "metric": [
        "total_matches",
        "total_goals",
        "avg_goals_per_match",
        "biggest_victory_margin",
        "top_winning_team",
        "most_red_cards_team",
        "zero_goal_matches",
        "knockout_penalty_pct"
    ],
    "value": [
        df.shape[0],
        df["total_goals"].sum(),
        round(df["total_goals"].mean(), 2),
        df["goal_difference"].max(),
        wins.index[0],
        most_red_cards.index[0],
        df[df["total_goals"] == 0].shape[0],
        round(percentage, 1)
    ]
})

summary

                   metric   value
0           total_matches     964
1             total_goals    2720
2     avg_goals_per_match    2.82
3  biggest_victory_margin       9
4        top_winning_team  Brazil
5     most_red_cards_team  Brazil
6       zero_goal_matches      78
7    knockout_penalty_pct    13.5

In [21]:
df["decade"] = (df["Year"] // 10) * 10

by_decade = df.groupby("decade").agg(
    total_matches=("total_goals", "count"),
    total_goals=("total_goals", "sum")
).reset_index()

by_decade

   decade  total_matches  total_goals
0    1930             53          224
1    1950             83          354
2    1960             64          178
3    1970            108          294
4    1980            104          278
5    1990            168          427
6    2000            128          308
7    2010            192          485
8    2020             64          172

In [22]:
summary.to_csv("output/wc_summary.csv", index=False)
by_decade.to_csv("output/wc_by_decade.csv", index=False)

print("Exportado")

Exportado